#!/usr/bin/env python3
"""
Test script to install VLC via App Center using the desktop automation framework.
This executes the workflow generated by the Desktop Automation Architect AI.
"""

from tasks.install_app import setup, execute, cleanup
from loguru import logger

def main():
    """Execute VLC installation workflow."""
    
    # Workflow configuration from the execution plan
    args = {
        "app_name": "VLC",
        "package_name": "vlc",
        "password": "rgukt"
    }
    
    logger.info("="*60)
    logger.info("Starting VLC Installation Workflow")
    logger.info("="*60)
    logger.info(f"Task: Install {args['app_name']} via App Center")
    logger.info(f"Package: {args['package_name']}")
    logger.info(f"Environment: Ubuntu 24.04 GNOME")
    logger.info("="*60)
    
    # Setup resources
    logger.info("Initializing automation resources...")
    resources = setup()
    
    try:
        # Execute the installation with enhanced verification
        logger.info("Executing installation workflow...")
        result = execute(args, resources)
        
        if result:
            logger.info("✅ VLC Installation Workflow COMPLETED SUCCESSFULLY")
            logger.info("Verification confirmed VLC is installed")
            
            # Now handle log file movement
            logger.info("\nMoving installer logs to ~/logs folder...")
            import subprocess
            import os
            
            # Create logs directory if it doesn't exist
            logs_dir = os.path.expanduser("~/logs")
            os.makedirs(logs_dir, exist_ok=True)
            logger.info(f"Created/verified logs directory: {logs_dir}")
            
            # Copy relevant log files
            log_sources = [
                "/var/log/apt/history.log",
                "/var/log/apt/term.log",
                "/var/log/dpkg.log"
            ]
            
            for log_file in log_sources:
                if os.path.exists(log_file):
                    try:
                        dest_file = os.path.join(logs_dir, os.path.basename(log_file))
                        subprocess.run(["cp", log_file, dest_file], check=True)
                        logger.info(f"✅ Copied {log_file} to {dest_file}")
                    except Exception as e:
                        logger.warning(f"Could not copy {log_file}: {e}")
            
            logger.info("\n" + "="*60)
            logger.info("WORKFLOW EXECUTION SUMMARY")
            logger.info("="*60)
            logger.info("Status: SUCCESS")
            logger.info(f"VLC installed: YES")
            logger.info(f"Logs moved to: {logs_dir}")
            logger.info("="*60)
            
            return 0
        else:
            logger.error("❌ VLC Installation Workflow FAILED")
            return 1
            
    except Exception as e:
        logger.error(f"❌ Workflow execution error: {e}")
        logger.exception("Full error details:")
        return 1
        
    finally:
        # Clean up resources
        logger.info("Cleaning up automation resources...")
        cleanup(resources)
        logger.info("Workflow execution completed")

if __name__ == "__main__":
    exit(main())
